// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnimeDetail } from "./AnimeDetail";
import type { Pagination } from "./Pagination";

export type AnimeList = { pagination: Pagination; data: Array<AnimeDetail> };
