// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Anime } from "./Anime";
import type { Pagination } from "./Pagination";

export type AnimeSearchResult = { pagination: Pagination; data: Array<Anime> };
