// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Images } from "./Images";

export type Anime = {
  mal_id: bigint;
  url: string;
  images: Images;
  title: string;
  title_english: string | null;
  title_japanese: string | null;
  rating: string | null;
  synopsis: string | null;
  score: number | null;
  scored_by: bigint | null;
  rank: bigint | null;
  year: bigint | null;
};
