// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnimeDetail = {
  id: bigint;
  image_url: string;
  small_image_url: string;
  large_image_url: string;
  title: string;
  title_english: string | null;
  title_japanese: string | null;
  rating: string | null;
  synopsis: string | null;
  score: number | null;
  scored_by: bigint | null;
  rank: bigint | null;
  year: bigint | null;
  to_watch: boolean | null;
  watched: boolean | null;
  my_score: bigint | null;
};
