// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WebP = {
  image_url: string;
  small_image_url: string;
  large_image_url: string;
};
